
music= {
    "": "",
    "jingle bells": "https://youtu.be/gI438fS6uUc?list=RDgI438fS6uUc",
    "die with smile": "https://www.youtube.com/watch?v=kPa7bsKwL-c",
    "firework": "https://www.youtube.com/watch?v=49mSqHdSy5A",
    "blue": "https://www.youtube.com/watch?v=IpFX2vq8HKw",
    "blank": "https://www.youtube.com/watch?v=DrfAFXsH_-A",
    "shape of you": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    "blinding light": "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    "uptown funk": "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    "rolling in the deep": "https://www.youtube.com/watch?v=rYEDA3JcQqw",
    "someone like you": "https://www.youtube.com/watch?v=hLQl3WQQoQ0",
    "despacito": "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
    "perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "havana": "https://www.youtube.com/watch?v=HCjNJDNzw8Y",
    "senorita": "https://www.youtube.com/watch?v=Pkh8UtuejGw",
    "bad guy": "https://www.youtube.com/watch?v=DyDfgMOUjCI",
    "thinking out loud": "https://www.youtube.com/watch?v=lp-EO5I60KA",
    "hello": "https://www.youtube.com/watch?v=YQHsXMglC9A",
    "roar": "https://www.youtube.com/watch?v=CevxZvSJLk8",
    "shake it off": "https://www.youtube.com/watch?v=nfWlot6h_JM",
    "sorry": "https://www.youtube.com/watch?v=fRh_vgS2dFE",
    "girls like you": "https://www.youtube.com/watch?v=aJOTlE1K90k",
    "closer": "https://www.youtube.com/watch?v=PT2_F-1esPk",
    "love yourself": "https://www.youtube.com/watch?v=oyEuk8j8imI",
    "faded": "https://www.youtube.com/watch?v=60ItHLz5WEA",
    "let her go": "https://www.youtube.com/watch?v=RBumgq5yVrA",
    "cheap thrills": "https://www.youtube.com/watch?v=nYh-n7EOtMA",
    "lean on": "https://www.youtube.com/watch?v=YqeW9_5kURI",
    "stressed out": "https://www.youtube.com/watch?v=pXRviuL6vMY",
    "rockabye": "https://www.youtube.com/watch?v=papuvlVeZg8",
    "sugar": "https://www.youtube.com/watch?v=09R8_2nJtjg",
    "sorry not sorry": "https://www.youtube.com/watch?v=8jK0i5j6o1A",
    "attention": "https://www.youtube.com/watch?v=nfs8NYg7yQM",
    "new rules": "https://www.youtube.com/watch?v=k2qgadSvNyU",
    "wolves": "https://www.youtube.com/watch?v=dzq5w5_bV_c",
    "believer": "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "thunder": "https://www.youtube.com/watch?v=fKopy74weus",
    "counting stars": "https://www.youtube.com/watch?v=hT_nvWreIhg",
    "demons": "https://www.youtube.com/watch?v=mWRsgZuwf_8",
    "radioactive": "https://www.youtube.com/watch?v=ktvTqknDobU",
    "hall of fame": "https://www.youtube.com/watch?v=mk48xRzuNvA",
    "wake me up": "https://www.youtube.com/watch?v=IcrbM1l_BoI",
    "take me to church": "https://www.youtube.com/watch?v=PVjiKRfKpPI",
    "all of me": "https://www.youtube.com/watch?v=450p7goxZqg",
    "stay": "https://www.youtube.com/watch?v=8EJ3zbKTWQ8",
    "let me love you": "https://www.youtube.com/watch?v=SMs0GnYze34",
    "we don't talk anymore": "https://www.youtube.com/watch?v=3AtDnEC4zak",
    "treat you better": "https://www.youtube.com/watch?v=lY2yjAdbvdQ",
    "there's nothing holding me back": "https://www.youtube.com/watch?v=dT2owtxkU8k",
    "what do you mean": "https://www.youtube.com/watch?v=DK_0jXPuIr0",
    "i don't care": "https://www.youtube.com/watch?v=y83x7MgzWOA",
    "senorita": "https://www.youtube.com/watch?v=Pkh8UtuejGw",
    "bad habits": "https://www.youtube.com/watch?v=orJSJGHjBLI",
    "shivers": "https://www.youtube.com/watch?v=Il0S8BoucSA",
    "peaches": "https://www.youtube.com/watch?v=tQ0yjYUFKAE",
    "save your tears": "https://www.youtube.com/watch?v=XXYlFuWEuKI",
    "levitating": "https://www.youtube.com/watch?v=TUVcZfQe-Kw",
    "good for u": "https://www.youtube.com/watch?v=gNi_6U5Pm_o",
    "drivers license": "https://www.youtube.com/watch?v=ZmDBbnmKpqQ",
    "deja vu": "https://www.youtube.com/watch?v=cii6ruuycQA",
    "traitor": "https://www.youtube.com/watch?v=7lB-mpX7Tt0",
    "positions": "https://www.youtube.com/watch?v=tcYodQoapMg",
    "34+35": "https://www.youtube.com/watch?v=B6_iQvaIjXw",
    "mood": "https://www.youtube.com/watch?v=GrAchTdepsU",
    "dynamite": "https://www.youtube.com/watch?v=gdZLi9oWNZg",
    "butter": "https://www.youtube.com/watch?v=WMweEpGlu_U",
    "permission to dance": "https://www.youtube.com/watch?v=CuklIb9d3fI",
    "life goes on": "https://www.youtube.com/watch?v=-5q5mZbe3V8",
    "boy with luv": "https://www.youtube.com/watch?v=XsX3ATc3FbA",
    "fake love": "https://www.youtube.com/watch?v=7C2z4GqqS5E",
    "idol": "https://www.youtube.com/watch?v=ZRtdQ81jPUQ",
    "dna": "https://www.youtube.com/watch?v=MBdVXkSdhwU",
    "mic drop": "https://www.youtube.com/watch?v=kTlv5_Bs8aw",
    "blood sweat & tears": "https://www.youtube.com/watch?v=hmE9f-TEutc",
    "fire": "https://www.youtube.com/watch?v=ALj5MKjy2BU",
    "dope": "https://www.youtube.com/watch?v=BVwAVbKYYeM",
    "save me": "https://www.youtube.com/watch?v=GZjt_sA2eso",
    "not today": "https://www.youtube.com/watch?v=9DwzBICPhdM",
    "spring day": "https://www.youtube.com/watch?v=xEeFrLSkMm8",
    "run": "https://www.youtube.com/watch?v=wKysONrSmew",
    "i need u": "https://www.youtube.com/watch?v=doqS35FfcUE",
    "no more dream": "https://www.youtube.com/watch?v=rBG5L7UsUxA",
    "we are bulletproof pt.2": "https://www.youtube.com/watch?v=Z-4j5f6P7wA",
    "just one day": "https://www.youtube.com/watch?v=9AhM8v9yP0Y",
    "danger": "https://www.youtube.com/watch?v=43r6lXilbcQ",
    "war of hormone": "https://www.youtube.com/watch?v=9Yy8o1BeFaE",
    "boy in luv": "https://www.youtube.com/watch?v=2cTZTqBU1Rc",
}

if __name__ == '__main__':
    text = "play Senorita"
    song = (text.split("play")[1]).split(" ")
    print(song)
    print((' '.join(song[1:])).lower())
    # link = music[ ' '.join((song.replace(" ","")).lower())]
    # print(link)   



